name: Deploy to notowen EC2 instance
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Clean site directory on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: notowen.com
          username: ec2-user
          key: ${{ secrets.NOTOWEN_EC2_SSH_KEY }}
          script: |
            rm -rf ~/notowen.com/
            mkdir ~/notowen.com
        
      - name: Upload repo to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: notowen.com
          username: ec2-user
          key: ${{ secrets.NOTOWEN_EC2_SSH_KEY }}
          source: "."
          target: "~/notowen.com"

      - name: Run deploy script on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: notowen.com
          username: ec2-user
          key: ${{ secrets.NOTOWEN_EC2_SSH_KEY }}
          script: |
            set -e
            cd ~/notowen.com/site
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh
