name: Deploy to notowen EC2 instance
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Install pandoc on gh runner
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          cd site
          chmod +x scripts/convert_md.sh
          ./scripts/convert_md.sh

      - name: Upload repo to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: notowen.com
          username: ec2-user
          key: ${{ secrets.NOTOWEN_EC2_SSH_KEY }}
          source: "."
          target: "~/notowen.com"

      - name: Run deploy script on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: notowen.com
          username: ec2-user
          key: ${{ secrets.NOTOWEN_EC2_SSH_KEY }}
          script: |
            set -e
            cd ~/notowen.com/site
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh
